' Gambas module file

Public hResultadoInteligencia As Result

Public Sub ConfigurarGridInteligencia(grid As GridView)

  With grid
    .Header = True
    .Grid = True
    .Columns.Count = 3

    ' Configuración de columnas
    For i As Integer = 0 To 3
      Select Case i
        Case 0
          .Columns[i].Title = "Id"
          .Columns[i].Width = 0
        Case 1
          .Columns[i].Title = "Identificador"
          .Columns[i].Width = 400
        Case 2
          .Columns[i].Title = "Prompt"
          .Columns[i].Width = 300
      End Select
    Next
  End With

End

Public Sub ConsultaBBDDinteligencia()

  hResultadoInteligencia = m_OnOff_y_Red.meConn.Exec("SELECT * FROM inteligencia_artificial ORDER BY id_inteligencia DESC")
  FMain.ViewgridAI.Rows.Count = hResultadoInteligencia.Count
  FMain.ViewgridAI.Refresh()

End

Public Sub LimpiarCamposInteligencia()

  FMain.txtIdPrompt.Text = ""
  FMain.txtTemperatura.Text = ""
  FMain.txtAsistenteAI.Clear
  FMain.txtIdentificador.Clear
  FMain.txtAreaPrompt1.Clear

End

Public Sub PromptNuevo()

  ' Ocultamos/mostramos botones según sea necesario
  FMain.btnPromptNuevo.Visible = False
  FMain.btnPromptBorrar.Visible = False
  FMain.btnPromptGuardar.Visible = True
  FMain.btnPromptGuardarCambios.Visible = False

  ' Habilitamos los campos de entrada
  FMain.txtIdentificador.Enabled = True
  FMain.txtIdentificador.ReadOnly = False
  FMain.txtIdentificador.Background = Color.White
  FMain.txtAreaPrompt1.Clear
  LimpiarCamposInteligencia()

  ' Obtenemos el último ID y sumamos +1 para el nuevo registro
  hResultadoInteligencia = m_OnOff_y_Red.meConn.Exec("SELECT MAX(id_inteligencia) FROM inteligencia_artificial LIMIT 1")

  Dim Idn As Integer
  ' Si no hay ninguna entrada entonces arrancamos desde 0
  If hResultadoInteligencia["MAX(id_inteligencia)"] = Null Then
    Idn = 0
  Else
    Idn = CInt(hResultadoInteligencia["MAX(id_inteligencia)"]) + 1
  Endif

  FMain.txtIdPrompt.Text = Idn
  FMain.txtIdentificador.SetFocus

End
