' Gambas module file

' módulo de connexión a la red y de cerrar todos los rocesos abiertos para salir de la aplicación
Public meConn As New Connection

Public Sub OnRed() As Connection

  meConn.Type = "sqlite3"
  meConn.Host = User.Home & "/.gbpivot/"
  meConn.Name = "gbpivot.sqlite"
  meConn.Open()
  ' Configurar el modo de journal a DELETE
  meConn.Exec("PRAGMA journal_mode=DELETE")
  Return meConn
  'verificamos
Catch
  Message.Error("No se pudo conectar a la base de datos <strong>gbpivot.sqlite</strong>\n en: " & User.Home & "/.gbpivot/")
  Quit

End

Public Sub OffRed() As Connection

  meConn.Close
  meConn = Null

End

Public Sub CerrarTodo()
  ' Lo primero: actualizar el estado del proyecto en la base de datos

  If FMain.txtProyecto.Text Then
    Dim sProyectoActual As String = File.BaseName(FMain.txtProyecto.Text)
    Try m_OnOff_y_Red.meConn.Exec("UPDATE nombre_proyecto SET en_uso = FALSE WHERE nombre = &1", sProyectoActual)
  Endif

  ' Ahora realizamos las operaciones que podrían fallar

  ' Borrar carpetas del caché
  Try FMain.TerminalView.Input("rm -rf " & User.Home & "/.local/share/org.gambas.*" & "\n")
  Try FMain.TerminalView.Input("clear" & "\n")
  Wait 0.2

  ' Detener el proceso Bash
  If FMain.$Bash And If FMain.$Bash.State = Process.Running Then
    Try FMain.$Bash.Kill
    Wait 0.2
    If FMain.$Bash.State = Process.Running Then
      Try FMain.$Bash.Terminate
      Wait 0.2
      If FMain.$Bash.State = Process.Running Then
        Message.Warning("El proceso no pudo ser detenido.")
      Endif
    Endif
  Endif

  ' Limpiar la interfaz
  FMain.txtProyecto.Text = ""
  FMain.DirViewProyecto.Root = User.Home

  ' Finalmente cerrar la conexión y salir
  Try meConn.Close
  FMain.Close
  Quit

End
