' Gambas module file

' módulo de connexión a la red y de cerrar todos los rocesos abiertos para salir de la aplicación

Public Sub CerrarTodo()

  ' Borramos carpetas del caché
  FMain.TerminalView.Input("rm -rf " & User.Home & "/.local/share/org.gambas.*" & "\n")
  FMain.TerminalView.Input("clear" & "\n")
  Wait 0.2

  ' detiene el proceso Bash
  If FMain.$Bash And If FMain.$Bash.State = Process.Running Then
    FMain.$Bash.Kill
    Wait 0.2
    If FMain.$Bash.State = Process.Running Then
      FMain.$Bash.Terminate
      Wait 0.2
      If FMain.$Bash.State = Process.Running Then
        Message.Warning("El proceso no pudo ser detenido.")
      Endif
    Endif
  Endif
  '
  ' Cierra WebView
  If FMain.WebViewEditor <> Null Then
    FMain.WebViewEditor.Stop
    FMain.WebViewEditor = Null
  End If

  ' Finalmente cerrar formulario principal y salir de la aplicación
  FMain.Close
  Quit

End
