title: gbPivot
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs/just-the-docs

url: https://albertomoyano.github.io/gbPivot/

# Habilitar búsqueda
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3

# Custom head con Google Fonts y CSS inline
head_custom: |
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,400;1,500&family=IBM+Plex+Mono:wght@400;500;600&display=swap" rel="stylesheet">
  <style>
    body {
      font-family: 'IBM Plex Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif !important;
      font-size: 16px !important;
      font-weight: 400;
      line-height: 1.6 !important;
    }
    h1, h2, h3, h4, h5, h6 {
      font-family: 'IBM Plex Sans', sans-serif !important;
      font-weight: 600 !important;
    }
    h1 {
      font-size: 2.25rem !important;
      font-weight: 700 !important;
      line-height: 1.2 !important;
    }
    h2 {
      font-size: 1.875rem !important;
      font-weight: 600 !important;
      line-height: 1.3 !important;
    }
    h3 {
      font-size: 1.5rem !important;
      font-weight: 600 !important;
    }
    h4 {
      font-size: 1.25rem !important;
      font-weight: 500 !important;
    }
    code, pre, .highlight {
      font-family: 'IBM Plex Mono', 'Fira Code', 'Monaco', monospace !important;
      font-size: 14px !important;
    }
    .site-nav, .navigation-list {
      font-family: 'IBM Plex Sans', sans-serif !important;
      font-weight: 500 !important;
    }
    a {
      font-weight: 500 !important;
    }
  </style>
