title: gbPivot
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs/just-the-docs

url: https://albertomoyano.github.io/gbPivot/

# Habilitar búsqueda
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3

# Custom head con Google Fonts y CSS inline
  <style>
    body {
      font-size: 18px !important;
    }
  </style>
