title: gbPivot
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs/just-the-docs
color_scheme: bordo
include:
  - assets/css/custom.scss
url: https://albertomoyano.github.io/gbPivot/
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3

sass:
  load_paths:
    - _sass
